---
- name: Install docker on all nodes.
  hosts: swarm
  become: true

  vars_files:
    - config.yml

  roles:
    - role: geerlingguy.docker

- name: Setup manager nodes.
  import_playbook: tasks/manager.yml

- name: Setup worker nodes.
  import_playbook: tasks/worker.yml
